name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  test:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          make install
      - name: Static Code Linting with flake8
        run: |
          make lint
      - name: Unit Testing with pytest
        env:
          # add environment variables for tests
        run: |
          make test